version: '3.8'

services:
  # 1. Aplikasi PHP-FPM (Backend)
  app:
    build:
      context: .
      dockerfile: docker/production/Dockerfile
    container_name: domaintik_prod_app
    restart: always
    environment:
      APP_ENV: production
      APP_DEBUG: 'false'
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db

  # 2. Web Server Nginx (Frontend Server)
  web:
    image: nginx:alpine
    container_name: domaintik_prod_nginx
    restart: always
    ports:
      - "80:80" 
      # - "443:443" # Jika nanti pakai SSL
    volumes:
      - ./docker/production/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_assets:/var/www/html/public
    depends_on:
      - app

  # 3. Database
  db:
    image: postgres:15-alpine
    container_name: domaintik_prod_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pg_data_prod:/var/lib/postgresql/data
    # PENTING: Jangan expose port 5432 ke host di production demi keamanan!
    # ports:
    #   - "5432:5432" 

# Volume Sharing
volumes:
  pg_data_prod:
  static_assets: